/*
 * This source file was generated by the Gradle 'init' task
 */
package ca.antany.lib;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class LibVersionTest {
    @Test
    void test1() {
    	assertTrue(true);
    }
}
