pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/antany/gradlew-java-nexus-jenkins-sonar-sample.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    dir('ant-common') {
                        sh 'chmod +x ./gradlew'
                        sh './gradlew build'
                    }
                }
            }
        }
    }

    post {
        always {
            // Archive the build artifacts
            archiveArtifacts artifacts: '**/build/libs/*.jar', allowEmptyArchive: true
            // Clean up the workspace
            cleanWs()
        }
    }
}
