pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/antany/gradlew-java-nexus-jenkins-sonar-sample.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'e56827e4-9c5c-4bbd-8d0d-3ef52ae8aab0', passwordVariable: 'password', usernameVariable: 'username')]) {
                       dir('ant-common') {
                            sh 'echo $username'
                            sh 'chmod +x ./gradlew'
                            sh './gradlew build -PmavenUser=$username -PmavenPassword=$password'
                        }
                    }
     
                }
            }
        }
    }

    post {
        always {
            // Archive the build artifacts
            archiveArtifacts artifacts: '**/build/libs/*.jar', allowEmptyArchive: true
            // Clean up the workspace
            cleanWs()
        }
    }
}
