services:
  nexus:
    image: docker.io/sonatype/nexus3
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    environment:
      - NX_LOG_LEVEL=DEBUG
      - NX_DEBUG=true
  jenkins:
    user: "0:0"
    image: docker.io/jenkins/jenkins:lts-jdk17
    ports:
      - "8080:8080"
      - "50000:50000" 
    volumes:
      - jenkins-data:/var/jenkins_home
    restart: unless-stopped
  sonarqube:
    image: docker.io/sonarqube:community
    ports:
      - 9000:9000
    volumes:
      - sonar-qube-data:/opt/sonarqube/data
      - sonar-qube-extensions:/opt/sonarqube/logs
      - sonar-qube-data:/opt/sonarqube/extensions

volumes:
  nexus-data:
  jenkins-data:
  sonar-qube-logs:  
  sonar-qube-extensions:
  sonar-qube-data:
        