/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import ca.antany.lib.LibVersion;

public class App {
	public static void main(String[] args) {

		LibVersion v = new LibVersion();
		System.out.println(v.printVersion());

	}
}
